### ISSUE TITLE
How to specify the lat, lon, etc?

### ISSUE THREAD

**Issue by robinpaulson** [bbuhler/openweathermap-ical#2]
Hi, I read the readme, there is a line which says "To use it just call the root entry point of the server with same parameters as for onecall API of OpenWeatherMap."

Could you expand upon that please, I've read the relevant API docs and am not sure how to translate that to running this. Specifically, where and how are the parameters specified?

Or perhaps an example?

Cheers

**Comment by robinpaulson** [comment]
Do you mean something like this, on the command-line:
$ node --experimental-modules index.mjs lat=-36.9 lon=174 appid=3e29e62e2ddf6dd3d2ebd28aed069215 exclude=part

**Comment by bbuhler** [comment]
Hi @robinpaulson,

the node script starts a server which runs on port 3001.

After the server runs you can access it for example like that:
http://localhost:3001/?lat=52.527742&lon=13.3061924&lang=de&units=metric&appid={YOUR_API_KEY}

If you want to use that in Google Calendar or similar you need to deploy that on public accessible server.

**Comment by robinpaulson** [comment]
got it, cheers!
